### ISSUE TITLE
Scan/Parse

### ISSUE THREAD

**Issue by radroid** [radroid/simple-stock-tracker#1]
- [x] Scan (the last two weeks or the last week, up to you) from the “[newswire](https://www.prnewswire.com/news-releases/news-releases-list/)” website.
- [x] Parse news

**Comment by MelnNik** [comment]
https://github.com/radroid/simple-stock-tracker/blob/main/notebooks/Scan_Parse_Store.ipynb

1. `def page_parse()` for scaning [PRNewsWire](https://www.prnewswire.com/news-releases/news-releases-list/) and returning URLs of scanned articles to pass the into `url_parse()` function.
2. `def url_parse()`  for parsing each article and searching for mentioned tickers

**Comment by radroid** [comment]
This task is complete.
